// FAKE DATA
export const books = [
  {
    id: 1,
    title: "The Assassin's Blade",
    url: "https://m.media-amazon.com/images/I/814SmgahuoL._SL1500_.jpg",
    originalPrice: 18,
    salePrice: 14.95,
    rating: 4.5,
  },
  {
    id: 2,
    title: "Throne of Glass",
    url: "https://m.media-amazon.com/images/I/41C4lviVdTL._SY445_SX342_.jpg",
    originalPrice: 12,
    salePrice: null,
    rating: 5,
  },
  {
    id: 3,
    title: "Crown of Midnight",
    url: "https://m.media-amazon.com/images/I/81f4Y0+4ZgL._SY522_.jpg",
    originalPrice: 14.50,
    salePrice: null,
    rating: 5,
  },
  {
    id: 4,
    title: "Heir of Fire",
    url: "https://m.media-amazon.com/images/I/917htoXM49L._SY522_.jpg",
    originalPrice: 16,
    salePrice: 14,
    rating: 4.5,
  },
  {
    id: 5,
    title: "Queen of Shadows",
    url: "https://m.media-amazon.com/images/I/41jiWvYcbSL._SY445_SX342_.jpg",
    originalPrice: 20,
    salePrice: null,
    rating: 5,
  },
  {
    id: 6,
    title: "Empire of Storms",
    url: "https://m.media-amazon.com/images/I/51+w7SAvdjL._SY445_SX342_.jpg",
    originalPrice: 25,
    salePrice: 20.5,
    rating: 5,
  },
  {
    id: 7,
    title: "Tower of Dawn",
    url: "https://m.media-amazon.com/images/I/51HynL4rbVL._SY445_SX342_.jpg",
    originalPrice: 27,
    salePrice: 22,
    rating: 4,
  },
  {
    id: 8,
    title: "Kingdom of Ash",
    url: "https://m.media-amazon.com/images/I/91mBaxamFcL._SL1500_.jpg",
    originalPrice: 30,
    salePrice: 24.95,
    rating: 4.5,
  },
  {
    id: 9,
    title: "A Court of Thorns and Roses",
    url: "https://m.media-amazon.com/images/I/81A-T+X6ukL._AC_UL640_QL65_.jpg",
    originalPrice: 20,
    salePrice: 17.95,
    rating: 4.5,
  },
  {
    id: 10,
    title: "A Court of Mist and Fury",
    url: "https://m.media-amazon.com/images/I/81X7G446iEL._AC_UL640_QL65_.jpg",
    originalPrice: 22,
    salePrice: null,
    rating: 5,
  },
  {
    id: 11,
    title: "A Court of Wings and Ruin",
    url: "https://m.media-amazon.com/images/I/81-2EciBFwL._AC_UL640_QL65_.jpg",
    originalPrice: 25,
    salePrice: 22,
    rating: 5,
  },
  {
    id: 12,
    title: "A Court of Frost and Starlight",
    url: "https://m.media-amazon.com/images/I/81lbIOH6GiL._AC_UL640_QL65_.jpg",
    originalPrice: 26,
    salePrice: 23.95,
    rating: 4.5,
  },
];